version: '2.1'

networks:
  keycloak-network:

volumes:
    keycloak-postgres-data:
    keycloak-nginx-letsencrypt-ssl:

services:
  postgres:
    image: postgres
    container_name: postgres
    networks:
      - keycloak-network
    volumes:
      - keycloak-postgres-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=keycloak
      - POSTGRES_USER=keycloak
      - POSTGRES_PASSWORD=password1
    logging:
      options:
        max-size: "50m"
        max-file: "3"
    restart: unless-stopped
  keycloak:
    image: "mihaibob/keycloak:18.0.2-legacy"
    container_name: keycloak
    networks:
      - keycloak-network
    depends_on:
      - postgres
    environment:
      - DB_VENDOR=postgres
      - DB_ADDR=postgres
      - DB_USER=keycloak
      - DB_PASSWORD=password1
      - DB_DATABASE=keycloak
      - PROXY_ADDRESS_FORWARDING=true
      - KEYCLOAK_USER=admin
      - KEYCLOAK_PASSWORD=password2
    ports:
      - "8080:8080"
    logging:
      options:
        max-size: "50m"
        max-file: "3"
    restart: unless-stopped
  nginx:
    build:
      context: keycloak-nginx-lets-encrypt
    container_name: nginx
    networks:
      - keycloak-network
    depends_on:
      - keycloak
    volumes:
      - keycloak-nginx-letsencrypt-ssl:/etc/letsencrypt
    environment:
      - KEYCLOAK_HOST=keycloak
      - KEYCLOAK_PORT=8080
      - KEYCLOAK_DOMAIN
      - LE_EMAIL
      - LE_RENEW_OPTIONS
      - LE_RENEW_CRON_COMMAND
    logging:
      options:
        max-size: "50m"
        max-file: "3"
    ports:
      - "80:80"
      - "443:443"
    restart: unless-stopped
